### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by yyyxlj** [yifan123/IC-Conv#8]
Hi 
when i use ICConv to replace the traditional  convolution has this problem:

self.conv = ICConv2d(pattern[pattern_index], inplanes, planes,kernel_size=kernel_size, stride=stride, bias=False)
TypeError: 'NoneType' object is not subscriptable

how can i deal with this problem

**Comment by yifan123** [comment]
It seems that you do not define the variable 'pattern'---- Replied Message ***@***.***>Date01/06/2022 18:11 ***@***.***> ***@***.***>Subject[yifan123/IC-Conv] problem (Issue #8)
Hi
when i use ICConv to replace the traditional  convolution has this problem:
self.conv = ICConv2d(pattern[pattern_index], inplanes, planes,kernel_size=kernel_size, stride=stride, bias=False)
TypeError: 'NoneType' object is not subscriptable
how can i deal with this problem

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yifan123/IC-Conv/issues/8",
"url": "https://github.com/yifan123/IC-Conv/issues/8",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yyyxlj** [comment]
then  how to define the variable 'pattern'  
i apply pattern like your code:

pattern = None
pattern_index = -1
class Conv_ICConv2d(nn.Module):
       super().__init__()
        global pattern, pattern_index
        pattern_index = pattern_index + 1
        self.conv = ICConv2d(pattern[pattern_index], inplanes, planes,
                             kernel_size=kernel_size, stride=stride, bias=False)#在基础卷基处加入空洞卷积,dilation=dilation
        self.bn = nn.BatchNorm2d(planes)
        self.act = nn.SiLU() if act is True else (act if isinstance(act, nn.Module) else nn.Identity())
        pattern_index = pattern_index + 1

**Comment by yifan123** [comment]
You can load pattern like this https://github.com/yifan123/IC-Conv/blob/master/model/ic_resnet.py#L96
